on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o reposit√≥rio do Git
        uses: actions/checkout@v2

      - name: executando o lint para verificar se a erros
        run: npx eslint .

      - name: Run Tests
        run: |
          npm install 
          npm test